CREATE DATABASE IF NOT EXISTS CarPlateDB;
USE CarPlateDB;

CREATE TABLE Funcionario (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(80) NOT NULL,
    EDV CHAR(8) NOT NULL,
    Senha LONGTEXT,
    Salt VARCHAR(200),
    Adm BIT NOT NULL,
    FOREIGN KEY (EnderecoID) REFERENCES Endereco(ID),
    FOREIGN KEY (TipoFuncionarioID) REFERENCES TipoFuncionario(ID)
);

CREATE TABLE Carro (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Cor VARCHAR(50) NOT NULL,
    Placa VARCHAR(7) NOT NULL,
    Modelo VARCHAR(100),
    Ano SMALLINT NOT NULL,
    FOREIGN KEY (FuncionarioID) REFERENCES Funcionario(ID)
);
